### ISSUE TITLE
Clarification1: Motivation to use absolute difference

### ISSUE THREAD

**Issue by mbharatheesha** [poornimajd/synchronization#1]
So, in [this line](https://github.com/poornimajd/synchronization/blob/2ef88a832dfbefeccac8ad68dce3f6cf2ee1665f/lidar_gen.py#L32) and [this line](https://github.com/poornimajd/synchronization/blob/2ef88a832dfbefeccac8ad68dce3f6cf2ee1665f/cam_gen.py#L31), I see that the delta is computed as an absolute difference between sync event time and the lidar/cam message time. I was curious what the motivation for this is, given the sync event is _always_ going to be greater than the message time stamp.

**Comment by poornimajd** [comment]
> given the sync event is _always_ going to be greater than the message time stamp.


Yes this is true,I had just used it while debugging some part of the code and forgot to remove it.It is not needed.
